import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.scss";

const inter = localFont({
  src: [
    {
      path: "../assets/fonts/Inter-Regular.ttf",
      weight: "400",
    },
    {
      path: "../assets/fonts/Inter-Medium.ttf",
      weight: "500",
    },
    {
      path: "../assets/fonts/Inter-Bold.ttf",
      weight: "700",
    },
  ],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  className={inter.className}>
        {children}
      </body>
    </html>
  );
}
